### PR TITLE
refactor: Add langcode getter to InfiniteStreamRecognizeOptions sample

### LINKED ISSUE #734: InfiniteStreamRecognize sample improvment
The sample about the usage of `StreamingRecognizeRequest` defined on `InfiniteStreamRecognize.java`, refers to the private element `langCode` from`InfiniteStreamRecognizeOptions`. Should be better to make a getter from the attribute and call the getter instead.

### PR DESCRIPTION
**Pull request by latra**
Created a get method. Referred the getMethod from InfiniteStreamRecognize.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-speech/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #734 ☕️

### CODE REVIEW

**Comment by kweinmeister** [comment]
@latra thanks for your contribution! Please check the "Details" links above for the 2 checks that need to pass: signing the CLA, and updating your PR title to follow the conventionalcommits.org standard.

For the PR title, I might suggest something like: `refactor: Add langcode getter to InfiniteStreamRecognizeOptions sample`

**Comment by latra** [comment]
@kweinmeister thanks! I already signed the CLA. I assume that the rescan is some action that you have to take? Or there is any button that I've to click? :) Also as you can see I changed the title.

**Comment by nicain** [comment]
@latra Do you need help modifying your PR to conform to the Conventional Commits requirement? Reach out if I can be of assistance!

**Comment by nicain** [comment]
@latra Just checking in one more time about your PR. Let me know if you would like help getting this merged.

**Comment by nicain** [comment]
Closing this PR for now. @latra feel free to reach out and reopen if this comes up again!

**Comment by latra** [comment]
Wops, sorry @nicain , I didn't realize. I'm not really sure about how to change the PR to conform to the Conventional Commits. Any help will be appreciated

**Comment by kweinmeister** [comment]
Hi @latra, you can follow the instructions [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages) and use the current title of this PR for your commit message.

**Pull request closed without merging**
