### PR TITLE
build: include sample-gen tests

### PR DESCRIPTION
**Pull request by chingor13**

### CODE REVIEW

**Comment by chingor13** [comment]
Blocked on https://github.com/googleapis/sample-tester/issues/131 and https://github.com/googleapis/sample-tester/issues/132

**Comment by nnegrey** [comment]
For the samples directory structure. 

I wonder if we should have something like:

- samples/
  - cloud-client/
  - beta/

or 
- samples/
  - v1/
  - v1p1beta1/

Easier to keep the ga vs. beta samples separate and keep the pom.xml s up to date. 
Also potentially if tutorials get autogenerated down the line and microphone streaming samples live separately. Thoughts?

Personally I don't like long package names, but that's my own opinion to shorten: `com/google/cloud/examples/speech` --> `com/examples/speech`

**Comment by nnegrey** [comment]
Plus other Java folks:
@kurtisvg 
@lesv 
@averikitsch
@dzlier-gcp
(Though I don't think all are part of googleapis)

**Comment by hzyi-google** [comment]
I originally made it look like `com/google/cloud/examples/speech` to follow patterns of samples in `google-cloud-examples` package.

Now that samples are put next to client libraries and there is one repo for one client library, this can definitely change.

(I still think `google` should be in the package name though).

**Comment by chingor13** [comment]
I haven't touched the Java package (namespace) for these generated classes.

As for separating the versioned classes, they are done so via the Java package so there's not a need for separating into separate maven modules. Note that the google-cloud-speech artifact contains all versioned gapic clients.

**Comment by beccasaurus** [comment]
A personal +1 to @nnegrey's suggestion for the following directory structure:
> **Note:** _I am **not** a Java programmer and dunno the idioms._ 

 - `.`
   - `...`
   - `samples/`
     - `v1/`
     - `v1p1beta1/`

----

I personally `<3` the following.

...but am _heavily biased_ because the following matches what we've done for the dynamic languages:

> **Note:** _I am **not** a Java programmer and dunno the idioms._ 

 - `.`
   - `...`
   - `samples/`
     - `resources/`
        - `common_file_used_by_samples.csv`
     - `v1/`
       - `pom.xml`
       - `src/`
          - `main/`
            - `...`
               - `cloud/`
                 - `examples/`
                   - `speech/`
                     - `TryMeSample.java`
       - `test/`
         - `try_me_sample.test.yaml`
     - `v1p1beta1/`
       - `...`

**Comment by chingor13** [comment]
The way the CLI arguments are constructed, the sample resources folder needs to be at the same level as the `pom.xml` (where the `mvn exec:java` command is run from).

**Comment by chingor13** [comment]
> The way the CLI arguments are constructed, the sample resources folder needs to be at the same level as the `pom.xml` (where the `mvn exec:java` command is run from).

I guess it's not entirely true. I could create a parent pom at the root samples directory which would be running the `mvn exec:java` command. The child poms would be used to compile/install the test files. This is a bunch more structure to maintain and duplicate across all the clients.

**Comment by beccasaurus** [comment]
Makes sense! Well then, I like it how it is ;)

> The way the CLI arguments are constructed, ...

At some point in the future, if we add a separate main() entrypoint (à la "AppChooser") for samples, maybe choices could be revisited if need be?

> This is a bunch more structure to maintain and duplicate across all the clients.

😫 Yeah, no, let's not :)

**Pull request closed without merging**
